name: Build Drift

on:
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install packages
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Build the Docker image
        run: docker build -t drift:${{ github.sha }} .